### ISSUE TITLE
CsvWriter "No such a method" 

### ISSUE THREAD

**Issue by Nem2s** [osiegmar/FastCSV#3]
I think that I found a bug inside the class CsvWriter:
```
"Caused by: java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
                                                                             at de.siegmar.fastcsv.writer.CsvWriter.append(CsvWriter.java:148)"
```

I doesn't work on android 7.0 but it works on android 8.0, same phone.
I already tried forcing Android Studio working with Java VERSION_1_8 and VERSION_1_7 but it's still the same.

**Comment by osiegmar** [comment]
That's odd. The method `java.io.File#toPath` **is** part of the Java 7 api (see [Java 7 doc](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#toPath())). But in android-land, this method is available only since API 26 (see [Android doc](https://developer.android.com/reference/java/io/File.html#toPath())) -- which is indeed Android 8.0.

As I do not have any android devices to test, I do not plan to add explicit support for it.

But you could try to use the method `de.siegmar.fastcsv.writer.CsvWriter#append(java.io.Writer)` and pass a `java.io.FileWriter` instance.

**Comment by Nem2s** [comment]
I can confirm that using a FileWriter solved the issues.
Thank you very much!

**Comment by joshualyon** [comment]
@osiegmar this also seems to impact the `CsvReader.parse()` methods where a `File` or `Path` are passed in. 

And from what I can tell `Objects.requireNonNull()` was also only added in API 19 (Android 4.4) whereas many devs support back to API 14.

If you change your mind about supporting Android devices, Google makes virtual devices available via the [Android Emulator](https://developer.android.com/studio/run/managing-avds.html).

**Comment by androidovshchik** [comment]
> @osiegmar this also seems to impact the `CsvReader.parse()` methods where a `File` or `Path` are passed in.
> 
> And from what I can tell `Objects.requireNonNull()` was also only added in API 19 (Android 4.4) whereas many devs support back to API 14.
> 
> If you change your mind about supporting Android devices, Google makes virtual devices available via the [Android Emulator](https://developer.android.com/studio/run/managing-avds.html).

Kotlin solution

```
val csvReader = CsvReader()
                    csvReader.setFieldSeparator(';')
                    csvReader.parse(BufferedReader(FileReader(path))).use { csvParser ->
                        while (true) {
                            val row = csvParser.nextRow() ?: break
                            println("Read line: $row")
                        }
                    }
```

**Comment by davrukin** [comment]
I also fixed this by replacing [FileUtils.deleteDirectory()](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html#deleteDirectory(java.io.File)) with [File.deleteRecursively()](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/delete-recursively.html).
